version: '3.8'

services:
  mysqldb:
    container_name: database
    build: database/
    restart: always
    ports:
      - 3306:3306
    networks:
      - contact-management-network
    environment:
      MYSQL_DATABASE: user-management
      MYSQL_ROOT_PASSWORD: admin
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
      
  backend:
    container_name: backend
    restart: always
    build: backend/
    ports:
      - "8080:8080"
    networks:
      - contact-management-network
    depends_on:
      mysqldb:
        condition: service_healthy
    environment:
      SPRING_APPLICATION_JSON: '{
        "spring.datasource.url"  : "jdbc:mysql://database:3306/user-management?allowPublicKeyRetrieval=true&useSSL=false",
        "spring.datasource.username" : "root",
        "spring.datasource.password" : "admin",
        "spring.jpa.properties.hibernate.dialect" : "org.hibernate.dialect.MySQLDialect",
        "spring.jpa.hibernate.ddl-auto" : "update"
        }'

  frontend:
    container_name: frontend
    build: frontend/
    ports:
      - "3000:3000"
    networks:
      - contact-management-network
    depends_on:
      - backend
      
networks:
  contact-management-network: