on:
  # Trigger analysis when pushing in master or pull requests, and when creating
  # a pull request. 
  push:
    branches:
      - main
  pull_request:
      types: [opened, synchronize, reopened]
jobs:
  sonarqube:
    name: SonarQube Build
    runs-on: ubuntu-latest
    steps:
    - name: Checkout 
      uses: actions/checkout@master  
      with:
      # Disabling shallow clone is recommended for improving relevancy of reporting
        fetch-depth: 0
    - name: Create docker image
      run: 
    # - name: SonarQube Scan
    #   uses: sonarsource/sonarqube-scan-action@master
    #   env:
    #     SONAR_HOST_URL: ${{ secrets.SONAR_HOST }}
    #     SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
    #   with:
    #     projectBaseDir: frontend/
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_TOKEN }}
    - name: Build and push
      uses: docker/build-push-action@v5
      with:
        context: backend/
        push: true
        tags: tharindu1989/contact-app-backend:latest
  
